const Router = require('express')
const router = new Router()
const productRouter = require('./productRouter')
const brandRouter = require('./brandRouter')
const widthRouter = require('./widthRouter')
const heightRouter = require('./heightRouter')
const diametrRouter = require('./diametrRouter')
const indexRouter = require('./indexRouter')
const speedRouter = require('./speedRouter')
const viletRouter = require('./viletRouter')
const diumRouter = require('./diumRouter')
const krepQuanRouter = require('./krepQuanRouter')
const widthDiskRouter = require('./widthDiskRouter')
const diskRouter = require('./diskRouter')
const typeRouter = require('./typeRouter')
const thornsRouter = require('./thornsRouter')
const seasonalityRouter = require('./seasonalityRouter')
const brandDiskRouter = require('./brandDiskRouter')
const diametrDiskRouter = require('./diametrDiskRouter')
const diametrDiskKrepRouter = require('./diametrDiskKrepRouter')

router.use('/height', heightRouter)
router.use('/diametr', diametrRouter)
router.use('/width', widthRouter)
router.use('/index', indexRouter)
router.use('/speed', speedRouter)
router.use('/brand', brandRouter)
router.use('/product', productRouter)
router.use('/vilet', viletRouter)
router.use('/dium', diumRouter)
router.use('/krep_quan', krepQuanRouter)
router.use('/disk', diskRouter)
router.use('/type', typeRouter)
router.use('/thorn', thornsRouter)
router.use('/seasonality', seasonalityRouter)
router.use('/width_disk', widthDiskRouter)
router.use('/brand_disk', brandDiskRouter)
router.use('/diametr_disk', diametrDiskRouter)
router.use('/diametr_disk_krep', diametrDiskKrepRouter)

module.exports = router